### ISSUE TITLE
Welcome to wpf2b

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/wordpress-fail2ban#1]
Hello @lkraav !

I've just realized you starred this repo.

Could I help you to set it up (for free) ?

**Comment by lkraav** [comment]
Thanks @szepeviktor loving the enthusiasm. I came across your PHP translation surfing around fail2ban issues. I don't have immediate plans to set wordpress-fail2ban up though, since not sure how it will in the existing infrastructure.

**Comment by szepeviktor** [comment]
OK.

> how it will in the existing infrastructure.

It is a very strict, it may catch 101% of all attackers :smile:

**Comment by szepeviktor** [comment]
> I came across your PHP translation

Oh! Miniban https://github.com/szepeviktor/wordpress-fail2ban/tree/master/miniban
It has several methods to block IP-s.
