### ISSUE TITLE
You are free to try this WAF

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/wordpress-fail2ban#3]
Hello @Kladizkov
In your wpcli video you are using iTheme's Security.
I was contributing to it when it was called Better WordPress Security. Then I've realized that available WordPress security plugins are liberal, *fits-all* solutions.

This waf blocks 50 attack vectors. It triggers Fail2ban (a linux daemon) but you may use the included Miniban class although you are required to install it manually.

It consists of two php files:
- an HTTP analyzer - load it from your wp-config
- an MU plugin - copy it to wp-content/mu-plugins/

Feel free to ask for support.

All the best to you!

**Comment by szepeviktor** [comment]
Hello @chesio!

I would welcome a test suite for the two PHP classes.

**Comment by chesio** [comment]
Hi Viktor,

I have little experience in writing test suites :-) Anyway, I find your project interesting and if I'll ever feel like contributing, I'll surely submit a pull request.
